spring:
  application:
    name: order-api
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/orderdb?authSource=admin
      database: orderdb
  kafka:
    bootstrap-servers: localhost:9094
    group-id: order-group
    auto-offset-reset: earliest
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual_immediate
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG